# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-12-17 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingrediente', '0001_initial'),
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='ingredientes',
            field=models.ManyToManyField(to='ingrediente.Ingrediente'),
        ),
    ]
