# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-12-18 02:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingrediente', '0002_auto_20211218_0123'),
        ('pizza', '0002_pizza_ingredientes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='ingredientes',
        ),
        migrations.AddField(
            model_name='pizza',
            name='ingredientes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ingrediente.Ingrediente'),
            preserve_default=False,
        ),
    ]
