# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-12-18 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingrediente', '0003_auto_20211218_1236'),
        ('pizza', '0003_auto_20211218_0207'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pizza',
            options={'ordering': ['nombre']},
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='ingredientes',
        ),
        migrations.AddField(
            model_name='pizza',
            name='ingredientes',
            field=models.ManyToManyField(to='ingrediente.Ingrediente'),
        ),
    ]
