# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-12-18 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingrediente', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingrediente',
            name='categoria',
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
