# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-12-18 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingrediente', '0002_auto_20211218_0123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingrediente',
            options={'ordering': ['nombre']},
        ),
        migrations.RemoveField(
            model_name='ingrediente',
            name='id',
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='nombre',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
