# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-12-19 20:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingrediente', '0003_auto_20211218_1236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingrediente',
            options={},
        ),
    ]
